"""Add location columns to booking and provider

Revision ID: 32db174a5800
Revises: 409b9a838c94
Create Date: 2026-01-03 15:38:10.908258

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32db174a5800'
down_revision = '409b9a838c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('providers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('providers', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'longitude')
    op.drop_column('providers', 'latitude')
    op.drop_column('bookings', 'longitude')
    op.drop_column('bookings', 'latitude')
    # ### end Alembic commands ###
