"""Add custom_price to ProviderServicesDB

Revision ID: 409b9a838c94
Revises: 20241214_booking_system
Create Date: 2026-01-03 15:19:35.174705

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '409b9a838c94'
down_revision = '20241214_booking_system'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_services', sa.Column('custom_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_services', 'custom_price')
    # ### end Alembic commands ###
