"""add_rating_to_bookings

Revision ID: ab12cd34ef56
Revises: dc89ed5e01fc
Create Date: 2026-01-03 23:05:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ab12cd34ef56'
down_revision = 'dc89ed5e01fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('review_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'review_comment')
    op.drop_column('bookings', 'rating')
    # ### end Alembic commands ###
